// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxetwpgdiurmuvtrrzzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZXR3cGdkaXVybXV2dHJyenpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjE4MDgsImV4cCI6MjA2NTMzNzgwOH0.o4edFJsbDX82nM_vIZNoAw4xmV8oUcFKGmeFSW5HPwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);